# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

on: ["push","pull_request"]

name: build

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 10.x
      - run: npm ci
      - run: npm run coveralls
      - name: Coveralls GitHub Action
        if: github.repository == 'Joopajoonas/Software-Testing-Assignment'
        uses: coverallsapp/github-action@v1.1.2 
        with:
          github-token: ${{ github.token }}
